### ISSUE TITLE
Comments alignment/display is off.

### ISSUE THREAD

**Issue by toddgrotenhuis** [pimoore/microdotblog-hitchens#1]
Example: 
![image](https://user-images.githubusercontent.com/165077/149425076-4f0c3f5d-7ce2-4e2e-aedc-f64db99931ed.png)
https://blog.grotenhuis.info/2021/09/19/our-friends-kids.html

**Comment by pimoore** [comment]
@toddgrotenhuis Thanks for reporting, I’ve got this fixed but will take a look at your other issue before committing the changes.

**Comment by pimoore** [comment]
[Fixed](https://github.com/pimoore/microdotblog-hitchens/commit/1fdf3c991a563fd1cf495fcc15c54a95649414d8)
