### ISSUE TITLE
Duplicate unique identifiers

### ISSUE THREAD

**Issue by svendahlstrand** [pimoore/microdotblog-hitchens#12]
The same `id` attribute, *main*, is used on [the `article` element](https://github.com/pimoore/microdotblog-hitchens/blob/f4cbee451c9e87f9dcdc5bb14c0a3874befcb033/layouts/partials/li.html#L1). On listing pages, like the homepage, this results in duplicate unique identifiers. This is not allowed according to the [HTML speciifcaiton](https://html.spec.whatwg.org/multipage/dom.html#global-attributes:the-id-attribute-2):

> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace.

In addition to generating validation errors, this has consequences for advanced users who want to customize the theme with CSS or JavaScript. For example, fetching an element with `document.getElementById('main')` makes little sense when there's more than one element having the same `id` attribute set.

I propose having unique identifiers for the `article` elements or just getting rid of the attribute.

This, of course, is not a high-priority bug. 😊

**Comment by pimoore** [comment]
Thanks Sven!  This has been fixed by removing the attribute, and will be included in the next theme update.
