### ISSUE TITLE
embeds scaling on mobile browser

### ISSUE THREAD

**Issue by toddgrotenhuis** [pimoore/microdotblog-hitchens#16]
Not adjusting for screen width. E.g.: https://blog.grotenhuis.info/2022/01/28/good-morning.html

![image](https://user-images.githubusercontent.com/165077/151675963-f64cc04c-19f2-440f-968a-8c4914455500.png)

**Comment by pimoore** [comment]
Thanks Todd, I’m going to have test this with Tufte and see if it’s an issue there as well.

**Comment by pimoore** [comment]
This is fixed, and will be available in the next update.
