### ISSUE TITLE
Is there a way to turn off Dropcaps on a post?

### ISSUE THREAD

**Issue by ghost** [pimoore/microdotblog-hitchens#3]
I really like Dropcaps on a long-form post, but if it's something like a poem it ruins the layout of the poem. I was wondering if there was a way to make it not use them but still have a title?

**Comment by pimoore** [comment]
@timscrawls As someone who also writes poetry I love this idea, thanks for suggesting it!  I know there’s a way to accomplish this, just going to figure out the easiest.

**Comment by ghost** [comment]
Sounds good, thanks for the great theme, I already have it all tweaked out and I'm loving it.

**Comment by pimoore** [comment]
Thanks Tim, glad you’re enjoying it! 🙏

**Comment by pimoore** [comment]
This is fixed and will be included in the next update!

Similar to the excerpt, by adding a custom ```<!--poetry-->``` tag before typing the actual post content, it will mark the div with a poetry ID and that will ensure dropcaps are disabled.
