### ISSUE TITLE
Book covers look misaligned in the bookshelves pages

### ISSUE THREAD

**Issue by jrcruciani** [pimoore/microdotblog-hitchens#7]
When displaying shelves on the site the covers are aligned below the expected location 

![8CBAB126-CDBE-432A-91A0-147A26C21693](https://user-images.githubusercontent.com/45102441/149597586-8f990585-7f6b-477b-950a-12ec30ab29ea.jpeg)
![D70BECFF-D9B8-4D30-B9C6-8DE4F32DD268](https://user-images.githubusercontent.com/45102441/149597591-22caab8b-17b0-4876-9907-95d2b47188d4.jpeg)

**Comment by pimoore** [comment]
Is this using Moondeer’s plugin or just the built in option?

**Comment by jrcruciani** [comment]
The built-in “Include books on page” option, no plug-ins

**Comment by pimoore** [comment]
Thanks, that should be straightforward to fix depending how the html elements are setup.

**Comment by pimoore** [comment]
This is fixed, it will be included in the next update!
