### ISSUE TITLE
Add built-in support for Conversation on Micro.blog plug-in

### ISSUE THREAD

**Issue by svendahlstrand** [pimoore/microdotblog-hitchens#9]
This is just an idea, and maybe not a good one. 😊 But [this conversation on Micro.blog](https://micro.blog/toddgrotenhuis/12377254) made me think that "hey, Hitchens could have built-in support for my [Conversation on Micro.blog plug-in](https://github.com/svendahlstrand/plugin-conversation-on-mb)".

A snippet like this would check if the plug-in is installed and, if so, include the partial:

```
{{ if templates.Exists "partials/conversation-link.html" }}
  {{ partial "conversation-link.html" . }}
{{ end }}    
```

So, if you like the idea, you could provide a sane default location for the *Conversation on Micro.blog* link in your theme. Maybe close to the Reply by email link?

For Hitchens folks that install the plug-in, the link would magically just appear.

**Comment by pimoore** [comment]
You sir, are on a roll.  Love it!

**Comment by pimoore** [comment]
Thanks Sven, this has been added and will be active at the next plugin update!
